### PR TITLE
Fix whitespace in descriptions of crypto-related audit criteria.

### PR DESCRIPTION
**Pull request by anforowicz**

### CODE REVIEW

**Comment by anforowicz** [comment]
@Manishearth, could you PTAL?

I suspect that my earlier  https://github.com/google/rust-crate-audits/pull/13 may have broken the `aggregate` workflow in the CI (*).  The problem in the earlier PR was caused by copy&pasting the descriptions into vim insert mode which didn't preserve the whitespace.

(*) After locally patching in `cargo vet` to add extra debugging statements:

```
$ git diff
diff --git a/src/main.rs b/src/main.rs
index 913e274..d1d6f29 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -194,6 +194,7 @@ fn report_error(error: &miette::Report) {
 }

 fn main() -> Result<(), ()> {
+    println!("cargo vet - local LUKASZA's version!!!");
     // NOTE: Limit the maximum number of blocking threads to 128, rather than
     // the default of 512.
     // This may limit concurrency in some cases, but cargo-vet isn't running a
@@ -2552,6 +2553,9 @@ fn do_aggregate_audits(sources: Vec<(String, AuditsFile)>) -> Result<AuditsFile,
     if errors.is_empty() {
         Ok(aggregate)
     } else {
+        for e in errors.iter() {
+            println!("ERROR: {e}");
+        }
         Err(AggregateErrors { errors })
     }
 }
      Err(AggregateErrors { errors })
```

I get the following errors when trying to run `cargo run -- vet aggregate --output-file ~/scratch/audits.toml ~/src/github/rust-crate-audits/sources.list`:

```
ERROR: criteria description mismatch for crypto-safe
https://chromium.googlesource.com/chromiumos/third_party/rust_crates/+/refs/heads/main/cargo-vet/audits.toml?format=TEXT:
All crypto algorithms in this crate have been reviewed by a relevant expert.

**Note**: If a crate does not implement crypto, use `does-not-implement-crypto`,
which implies `crypto-safe`, but does not require expert review in order to
audit for.
https://raw.githubusercontent.com/google/rust-crate-audits/main/manual-sources/google3-audits.toml:
All crypto algorithms in this crate have been reviewed by a relevant expert.
**Note**: If a crate does not implement crypto, use `does-not-implement-crypto`,
which implies `crypto-safe`, but does not require expert review in order to
audit for.
ERROR: criteria description mismatch for does-not-implement-crypto
https://chromium.googlesource.com/chromiumos/third_party/rust_crates/+/refs/heads/main/cargo-vet/audits.toml?format=TEXT:
Inspection reveals that the crate in question does not attempt to implement any
cryptographic algorithms on its own.

Note that certification of this does not require an expert on all forms of
cryptography: it's expected for crates we import to be "good enough" citizens,
so they'll at least be forthcoming if they try to implement something
cryptographic. When in doubt, please ask an expert.
https://raw.githubusercontent.com/google/rust-crate-audits/main/manual-sources/google3-audits.toml:
Inspection reveals that the crate in question does not attempt to implement any
cryptographic algorithms on its own.
Note that certification of this does not require an expert on all forms of
cryptography: it's expected for crates we import to be "good enough" citizens,
so they'll at least be forthcoming if they try to implement something
cryptographic. When in doubt, please ask an expert.
ERROR   × there were errors aggregating source audit files
```

**Comment by anforowicz** [comment]
FWIW the Chromium equivalent of changes in this PR can be found at https://chromium-review.googlesource.com/c/chromium/src/+/5341119

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
Please undo the removal of audits.toml

**Comment by Manishearth** [comment]
Actually if I merge this the CI job should autofix things.

**Comment by anforowicz** [comment]
> Please undo the removal of audits.toml

Ooops.  Not sure how that happened :-o.

> Actually if I merge this the CI job should autofix things.

Thanks.  Yes, the CI is green (as seen at https://github.com/google/rust-crate-audits/actions) and the new `audits.toml` is has been regenerated.

**Pull request merged**
